export enum ActionTypes {
  FETCH_USER_DATA_PENDING = "FETCH_USER_DATA_PENDING",
  FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS",
  FETCH_USER_DATA_FAILURE = "FETCH_USER_DATA_FAILURE",

  FETCH_USER_TWEETS_PENDING = "FETCH_USER_TWEETS_PENDING",
  FETCH_USER_TWEETS_SUCCESS = "FETCH_USER_TWEETS_SUCCESS",
  FETCH_USER_TWEETS_FAILURE = "FETCH_USER_TWEETS_FAILURE",

  LOGOUT_ACTION = "LOGOUT_ACTION",
}
